/**************************************************************** 
* Author: Nicholas Schaffner
* Last Modified: 08/25/20
* Description: This program creates a key file of specified length. The characters in the file generated are any of
*               the 27 allowed characters(A-Z and ' ') and are generated using the standard UNIX randomization methods.
*               The last character this program outputs is a newline. The syntax for this program is:
*               keygen keylength
*               keylength is the length of the key file in characters. This program outputs to stdout.
****************************************************************/

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

int main(int argc, char *argv[]){
    int currentIntValue;                                        /* Variable to hold the current integer value that is generated by rand() */
    int i = 0;                  
    char currentChar;                                           /* Variable to hold the current ASCII char equivalent to the integer value generated by rand() */

    srand(time(0));                                             /* Use the current time as the seed for the random generator */

    int keyLength = atoi(argv[1]);                              /* Convert the string argument after keygen into an integer. Please note, I utilized p.65 of the "All Block 4 Lectures in One PDF" lecture for this line */

    for(i = 0; i < keyLength; i++){
        currentIntValue = (rand() % 27 + 65);                   /* Generate a random number between 65-91, inclusive, and assign it to currentIntValue */

        if(currentIntValue == 91){                              /* If the current generated integer is 64, which is the '@' character, replace it with the value 32, which is the space character */                 
            currentIntValue = 32;
        }
        currentChar = currentIntValue;                          /* Set the currentChar equal to the current generated integer, which will set currentChar equal to its corresponding ASCII character */

        printf("%c", currentChar);                              /* Print out the currentChar */
    }

    printf("\n");                                               /* Print out a newline character, per the assignment specifications */
    
    return 0;
}